### ISSUE TITLE
Deploy Hexo To GIthub

### ISSUE THREAD

**Issue by NoXLaw** [YunYouJun/yunyoujun.github.io#101]
文章链接：<https://www.yunyoujun.cn/>

Hey yunyoujun, i have a problem in travis-ci,
$ git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
remote: Invalid username or password.
fatal: Authentication failed for 'https://dc2777cc99bea4bbceabaa078c20114388a7e5d9@github.com/NoXLaw/noxlaw.github.io.git/'
how to solve this problem?

**Comment by YunYouJun** [comment]
I have migrated from Travis-CI to [GitHub Actions](https://github.com/features/actions).

Github actions comes with GITHUB_TOKEN without having to deal with complex permissions issues.

If you want to refer to some deployment scripts, you can see [gh-pages.yml](https://github.com/YunYouJun/yunyoujun.github.io/blob/hexo/.github/workflows/gh-pages.yml).

**Comment by NoXLaw** [comment]
Thanks i just deploy hexo to github pages..
