### ISSUE TITLE
更改渲染器

### ISSUE THREAD

**Issue by atomicoo** [YunYouJun/yunyoujun.github.io#102]
首先感谢下老铁做的主题 hexo-theme-yun，风格很对我的口味。
不过我想问下，修改渲染器为 hexo-renderer-markdown-it 之后，文章的侧边栏目录好像就没法正常使用了，是不是不能换渲染器啊，如果是的话需要一些额外的扩展比如 支持emoji 之类的该怎么搞呢？

**Comment by YunYouJun** [comment]
主题相关内容请到 [hexo-theme-yun](https://github.com/YunYouJun/hexo-theme-yun) 处发起 ISSUE。

此前倒是有过一个类似的讨论。https://github.com/YunYouJun/hexo-theme-yun/issues/22#issuecomment-620933198

该 ISSUE 我将关闭，如果仍有问题可在主题处开启 ISSUE。
