### ISSUE TITLE
Git不能正常配置域名，网页全空白

### ISSUE THREAD

**Issue by huyukun-z** [YunYouJun/yunyoujun.github.io#110]
文章链接：<https://www.huyukun.top/>
问题提问：Git不能正常配置域名，就连hexo g和s都不行

以下的图片从2020-12-31之后60天后过期
详细展示：
 这是我在用Git配置的时候出现的很长的错误代码，这只是一部分：

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/Git1.png]

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/Git2.png]

然后我强制上传hexo d了之后，网页是这样的：

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/%E7%BD%91%E9%A1%B5%E6%98%AF%E8%BF%99%E6%A0%B7%E7%9A%84.png]

f12检查：

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/f12%E6%A3%80%E6%9F%A5.png]

网页源代码：

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/%E7%BD%91%E9%A1%B5%E6%BA%90%E4%BB%A3%E7%A0%81.png]

相当于我的网页是全空白的

现在来看看GitHub：

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/GitHub1.png]

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/GitHub2.png]

这些是没问题的，接下来还有DNS

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/DNS.png]

[https://hurricane-1304281920.cos.ap-guangzhou.myqcloud.com/%E7%BD%91%E7%AB%99%E5%9F%9F%E5%90%8D/www.huyukun.top/%E9%97%AE%E9%A2%98%E6%97%A5%E5%BF%97/2020-12-31/DNS1.png]

我改过主题配置文件_config.yml和yun文件夹里面的同样的主题配置文件，但是和我另一个网站来对比的话，是没什么问题的，就是这个网站成了这样，这个要怎么搞啊？还请大佬赐教~

新年快乐~

**Comment by YunYouJun** [comment]
请使用 `![](图片链接)` 的语法来显示图片预览图。
