### ISSUE TITLE
图床貌似挂了

### ISSUE THREAD

**Issue by FogFoge** [YunYouJun/yunyoujun.github.io#111]
在看你的博客的时候发现i.loli.net图床挂了

**Comment by YunYouJun** [comment]
试了试似乎基本都能打开，可能是线路问题？

**Comment by FogFoge** [comment]
我试试挂代理能不能用

**Comment by FogFoge** [comment]
直接用提示Load Error

**Comment by FogFoge** [comment]
挂国外代理就能用了，

**Comment by FogFoge** [comment]
谢啦！现在能用了！tks

**Comment by YunYouJun** [comment]
暂时没想到其他更好的图床解决方案。

**Comment by FogFoge** [comment]
话说云游君是配置了Server酱推送Issue吗？

**Comment by YunYouJun** [comment]
> 话说云游君是配置了Server酱推送Issue吗？

GitHub 酱自动发的邮件啊（

**Comment by FogFoge** [comment]
（AZ，是我孤陋寡闻了）

**Comment by YunYouJun** [comment]
感觉又拍云存储（领代金券）加 [PicGo](https://github.com/Molunerfinn/PicGo) 还不错，打算逐步迁移到这个方案上来。
