### ISSUE TITLE
使用hexo-algoliasearch 搜索失败控制台报以下错误，是为什么？

### ISSUE THREAD

**Issue by hqw567** [YunYouJun/yunyoujun.github.io#138]
使用[hexo-algoliasearch ](https://github.com/LouisBarranqueiro/hexo-algoliasearch)搜索失败控制台报以下错误，是为什么？
 请为我应该怎么去解决？
![image](https://user-images.githubusercontent.com/74847198/161417288-86b7745c-b294-4bf4-abc8-e3ecc8e76502.png)
![image](https://user-images.githubusercontent.com/74847198/161417293-42371c99-a502-4bfb-beff-f15cb6c30599.png)
![image](https://user-images.githubusercontent.com/74847198/161417295-60a6b520-06d4-4d95-b3d1-7952c2343a77.png)

**Comment by hqw567** [comment]
> 使用[hexo-algoliasearch ](https://github.com/LouisBarranqueiro/hexo-algoliasearch)搜索失败控制台报以下错误，是为什么？ 请为我应该怎么去解决？ ![image](https://user-images.githubusercontent.com/74847198/161417288-86b7745c-b294-4bf4-abc8-e3ecc8e76502.png) ![image](https://user-images.githubusercontent.com/74847198/161417293-42371c99-a502-4bfb-beff-f15cb6c30599.png) ![image](https://user-images.githubusercontent.com/74847198/161417295-60a6b520-06d4-4d95-b3d1-7952c2343a77.png)

**Comment by YunYouJun** [comment]
虽然但是，我觉得这个问题应该问 https://github.com/LouisBarranqueiro/hexo-algoliasearch 。
