### ISSUE TITLE
Url for posting blog

### ISSUE THREAD

**Issue by NoXLaw** [YunYouJun/yunyoujun.github.io#89]
How to post blog in this project ?

**Comment by YunYouJun** [comment]
Maybe you need to know some knowledge about hexo. You can find more info [here](https://hexo.io/).

Example, after you install hexo. You just need write post `xxx.md` in `source/_posts`.
Then use `hexo generate` to generate static files.

**Comment by YunYouJun** [comment]
If you do not plan to use this issue, I will close it.
