### ISSUE TITLE
How to post

### ISSUE THREAD

**Issue by NoXLaw** [YunYouJun/yunyoujun.github.io#90]
Command for post in _posts/share

If I want to post in _posts
Command : hexo new post "title"

And I want to post in _posts/share
Command : ??

And then, I want to change the home page on themes starry, how I can change ?
I want to change on the title home page

Thanks :*

**Comment by YunYouJun** [comment]
`share` folder is my custom folder. 
You can hexo new post "title". Then drag `title.md` to your custom folder(You can also name it something else).  Of course, you can also not use custom folders.

If you want to change theme `starry`, you can see some code in <https://github.com/YunYouJun/hexo-theme-starry/tree/master/layout>.
You can clone it and custom it, put it in `themes`. Of course, PR for `hexo-theme-starry` is welcome.

**Comment by NoXLaw** [comment]
![2019_12_23_12_09_21](https://user-images.githubusercontent.com/35652825/71337263-6f7faf00-257d-11ea-9336-f9cdccfb3d24.jpg)
I want to change this ..
But I don't know how I can change

**Comment by NoXLaw** [comment]
And I want to change a background in this themes

**Comment by YunYouJun** [comment]
Index banner code is [here](https://github.com/YunYouJun/hexo-theme-starry/blob/master/layout/_partial/banner.pug).
If you just want to change title, you can set title in [here](https://github.com/YunYouJun/yunyoujun.github.io/blob/hexo/_config.yml).

You can change background [here](https://github.com/YunYouJun/hexo-theme-starry/blob/13ac1698fa8fe63d99cef26d089c879c96c801fc/_config.yml#L177).
Or add 

```yaml
ui:
  bg_image:
    enable: true
    url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/alice-kirito-eugeo.jpg
```

in `source/_data/starry.yml`.

**Comment by NoXLaw** [comment]
Ok thanks, but I want to change text to..
![2019_12_23_13_30_44](https://user-images.githubusercontent.com/35652825/71340289-dd7da380-2588-11ea-83dd-51b7de8b377c.jpg)

**Comment by YunYouJun** [comment]
Change text(title) [here](https://github.com/YunYouJun/yunyoujun.github.io/blob/492e9486aa719549858e25d102d0b93b28c6b8ba/_config.yml#L6).

**Comment by NoXLaw** [comment]
I just changed it, but there is no change there

**Comment by YunYouJun** [comment]
I am sorry.
You should change it [here](https://github.com/YunYouJun/hexo-theme-starry/blob/13ac1698fa8fe63d99cef26d089c879c96c801fc/_config.yml#L80).

**Comment by NoXLaw** [comment]
![Screenshot_20191223-134228-picsay](https://user-images.githubusercontent.com/35652825/71341709-2df70000-258d-11ea-9566-be6f41f761b8.png)
Ok thank you very much, but i want to add icon Facebook, and whatsapp, 
I know where is the file location..
Just I want to add css file in this navbar, for add icon..
But how I can add css link in this project?

**Comment by NoXLaw** [comment]
Solved, thanks

**Comment by YunYouJun** [comment]
OK, good luck.
I will close it. If you have any questions about it, you can reopen it.

**Comment by NoXLaw** [comment]
Sorry, in source/css 
I don't find file css in here..
Where the css file?
