### ISSUE TITLE
Change css file

### ISSUE THREAD

**Issue by NoXLaw** [YunYouJun/yunyoujun.github.io#91]
How to add css file, in source/css
I don't find it the css file in here

**Comment by NoXLaw** [comment]
?

**Comment by YunYouJun** [comment]
You can find some file with `.styl` [here](https://github.com/YunYouJun/hexo-theme-starry/tree/master/source/css).
They are stylus file.
Stylus is a language to write css. Of course, you can write css directly in it.
More info about stylus [here](https://github.com/stylus/stylus).

**Comment by NoXLaw** [comment]
I want to add font awesome css..
But I don't know how I add this :"(

**Comment by YunYouJun** [comment]
Yeah, css cdn [here](https://github.com/YunYouJun/hexo-theme-starry/blob/13ac1698fa8fe63d99cef26d089c879c96c801fc/_config.yml#L128).

**Comment by NoXLaw** [comment]
![2019_12_23_15_18_05](https://user-images.githubusercontent.com/35652825/71345355-b7abcb00-2597-11ea-8339-a06ab16ae423.jpg)
![2019_12_23_15_18_44](https://user-images.githubusercontent.com/35652825/71345357-b8446180-2597-11ea-8fd2-dcc16729ef0a.jpg)
![2019_12_23_15_18_15](https://user-images.githubusercontent.com/35652825/71345358-b8446180-2597-11ea-97b4-7b5a194adde6.jpg)
I just add this css link "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" in _config.yml
But when I add fa-whatsapp in icon, not working, why?

**Comment by NoXLaw** [comment]
I just add `<a href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">font awesome css file</a>` in _config.yml, but not working when I add fa-whatsapp in icon..
Why?

**Comment by NoXLaw** [comment]
![2019_12_23_15_18_05](https://user-images.githubusercontent.com/35652825/71345836-fdb55e80-2598-11ea-8862-90d760150914.jpg)
![2019_12_23_15_18_44](https://user-images.githubusercontent.com/35652825/71345845-0312a900-2599-11ea-87e8-98774fb7e915.jpg)

**Comment by NoXLaw** [comment]
![2019_12_23_15_30_59](https://user-images.githubusercontent.com/35652825/71346000-68669a00-2599-11ea-8221-f4e16d7dbf34.jpg)
And I want change this text "我们一日日度过的所谓日常,实际上可能是接连不断的奇迹。 —— 《日常》" how I can change?

**Comment by NoXLaw** [comment]
![2019_12_23_15_30_59](https://user-images.githubusercontent.com/35652825/71346039-8633ff00-2599-11ea-9b72-25055a79ba99.jpg)

**Comment by YunYouJun** [comment]
Change words [here](https://github.com/YunYouJun/yunyoujun.github.io/blob/492e9486aa719549858e25d102d0b93b28c6b8ba/source/_data/starry.yml#L154).

**Comment by YunYouJun** [comment]
I think you missed `fab` before `fa-whatsapp` about icon.
Double-check how to use fontawesome.

**Comment by NoXLaw** [comment]
Yeah, before fa-whatsapp, I put `fa fa-whatsapp` but not working :"(

**Comment by YunYouJun** [comment]
`fab` not `fa`
I have test it and success.
😄

**Comment by NoXLaw** [comment]
That's cool, thanks :*
Oh ya, when i delete all Post in _posts, 
Why nothing has changed on the home page

**Comment by YunYouJun** [comment]
Are you sure that you regenerate by hexo and restart it?

**Comment by NoXLaw** [comment]
When I delete all post in _posts, 
then I try to check again on the home page, nothing changes or all posts are not deleted, why ??

**Comment by NoXLaw** [comment]
Ok this is work if I delete all in _posts/path/*

But after that, I get error..
![2019_12_23_19_01_27](https://user-images.githubusercontent.com/35652825/71357344-f2bdf680-25b7-11ea-8ac5-0d9b6b9a4eff.jpg)

**Comment by YunYouJun** [comment]
You can try
- Delete all files in `source/_posts`
- create `hello.md` in `source/_posts` to ensure at least 1 post
- restart your server

If it does n’t work, then I can do nothing.

**Comment by NoXLaw** [comment]
Thanks it's work :*
Oh ya, how to reset viewers count in footer?
And I want to add text in footer after viewers count, [ In bottom after viewers count ]

**Comment by YunYouJun** [comment]
I write some config, you can see [here](https://github.com/YunYouJun/hexo-theme-starry/wiki/Config).

Viewers count will be reset if you publish it.

**Comment by NoXLaw** [comment]
I want to edit your name to my name, in comments..
You can comment with GitHub or Valine if you dont have github account。
GITALK or VALINE
Related Issues not found

Please contact @YunYouJun to initialize the comment

How to edit this?

**Comment by YunYouJun** [comment]
[Here](https://github.com/YunYouJun/yunyoujun.github.io/blob/492e9486aa719549858e25d102d0b93b28c6b8ba/source/_data/starry.yml#L57).

In fact, many config can be found in `source/_data/starry.yml`.

**Comment by NoXLaw** [comment]
I just edit in source/_data/starry.yml
But nothing change in my localhost..

**Comment by NoXLaw** [comment]
Why?

**Comment by YunYouJun** [comment]
Maybe you didn't config client id and secret?
More config info see [gitalk](https://github.com/gitalk/gitalk).

**Comment by NoXLaw** [comment]
Thanks,
I want to configure algolia, but when I'm already on the algolia dashboard, I don't know what to do, I've got the appid & secret key,

**Comment by NoXLaw** [comment]
How to configure algolia?

**Comment by YunYouJun** [comment]
You can ref [this | theme-next](https://theme-next.org/docs/third-party-services/search-services#Algolia-Search).
