### ISSUE TITLE
留言板｜云游君的小站

### ISSUE THREAD

**Issue by YunYouJun** [YunYouJun/yunyoujun.github.io#98]
> 有什么话要对我说吗？可以直接在下方留言～

> 主题或其他项目请到对应 issue/discussions 中提问，无关内容将会被清除。

留言板移动至 Discussions #145。

**Comment by DaisyLoveMango** [comment]
我再试试issue评论

**Comment by MBRjun** [comment]
qwq

**Comment by china-haoxuan** [comment]
qaq为什么我的网站没有在大佬的网站上显示啊，奇怪（明明添加了啊）

**Comment by YunYouJun** [comment]
> qaq为什么我的网站没有在大佬的网站上显示啊，奇怪（明明添加了啊）

https://github.com/YunYouJun/friends/pull/29

**Comment by CRH6F-A-0464** [comment]
我的博客（Hydropowered Hub）域名已更换，申请更新友链
新域名： hydropwr.ca

**Comment by YunYouJun** [comment]
> 我的博客（Hydropowered Hub）域名已更换，申请更新友链
> 新域名： hydropwr.ca
> @YunYouJun

已更新，若日后更改可在此处 PR。
> https://github.com/YunYouJun/friends/blob/master/src/links.yml

**Comment by YunYouJun** [comment]
> 您好，请问这个主题的搜索框位置和鼠标样式应该怎样配置呀，还有如果我想引入雪花特效的话又应该怎样配置呢？:whee:

主题相关内容，请在此处提问。

> https://github.com/YunYouJun/hexo-theme-yun/discussions

**Comment by muyuanshan** [comment]
怎么增加一个点击图片放大的功能哇？

**Comment by YunYouJun** [comment]
> 怎么增加一个点击图片放大的功能哇？

主题相关内容，请在此处提问。

> https://github.com/YunYouJun/hexo-theme-yun/discussions

**Comment by emerisly** [comment]
请问大佬一个问题 我配置了5hr+了依然不知道怎么解决
想实现本地搜索功能
现已按照yun教程中的tips关闭engine search并添加local engine，也按照了https://github.com/wzpan/hexo-generator-search 中的说明install hexo-generator-search，并在root的config中添加了search的设置
现在的情况是hexo g后会报错 ./search.xml not found
`Start processing
FATAL {
  err: Error: ENOENT: no such file or directory, open './search.xml'
      at Object.openSync (node:fs:585:3)
      at Object.readFileSync (node:fs:453:35)
      at Hexo.module.exports`
我又试了在https://github.com/wzpan/hexo-generator-search 找到了一个search.xml的template https://github.com/wzpan/hexo-generator-search/blob/master/templates/search.xml 放在了root文件夹中，在这个情况下，本地搜索可以在localhost上能够成功使用搜索功能
但是hexo depoly后云端未显示任何搜索功能
在把手动加入root文件夹的search.xml删除后，依然会报错
请问我是有什么配置弄错了吗呜呜
感谢！

![image](https://user-images.githubusercontent.com/44758321/147375034-ff9e96cb-d0a8-4f41-ab50-b64271d3d0c2.png)

**Comment by Elonisme** [comment]
怎么把[John Doe]改成自己的名字啊？

**Comment by YunYouJun** [comment]
> 怎么把[John Doe]改成自己的名字啊？

请在主题对应仓库提问。

见 `_config.yml` 文件中的 `author`。

**Comment by ElegantLee** [comment]
大佬，你做的主题用了挺久的了，感觉非常棒。最近想起来改背景图片，按照文档配置了，但是并没有生效。我将图片放在source/images目录下和使用CDN图片链接都试过了，还是默认的背景图片，不知道是哪里没弄对。。。

**Comment by KING754** [comment]
所以，现在是为什么站里，都不挂评论了？因为政策吗？

**Comment by KING754** [comment]
现在是为什么站里，都不挂评论了？还是因为站出错了？还是别的什么原因？

chunk-72ZP56JR.js:1  ☁️ hexo-theme-yun 1.10.7  https://github.com/YunYouJun/hexo-theme-yun
waline.js:1 Uncaught TypeError: window.Waline.init is not a function
    at waline.js:1:130
    at y (chunk-72ZP56JR.js:1:782)
    at HTMLDocument.i (waline.js:1:84)

**Comment by YunYouJun** [comment]
> 现在是为什么站里，都不挂评论了？还是因为站出错了？还是别的什么原因？
> 
> chunk-72ZP56JR.js:1 ☁️ hexo-theme-yun 1.10.7 https://github.com/YunYouJun/hexo-theme-yun waline.js:1 Uncaught TypeError: window.Waline.init is not a function at waline.js:1:130 at y (chunk-72ZP56JR.js:1:782) at HTMLDocument.i (waline.js:1:84)

有哇。

**Comment by KING754** [comment]
可能是时候，看不到。网络不太稳吧。可能是。

**Comment by guLinga** [comment]
怎么把文章的目录放到右侧呢？

**Comment by YunYouJun** [comment]
> 怎么把文章的目录放到右侧呢？

参见使用 [Valaxy](https://github.com/YunYouJun/valaxy/)。
