### ISSUE TITLE
如何让yun主题支持数学公式

### ISSUE THREAD

**Issue by chenlvtang** [YunYouJun/yunyoujun.github.io#99]
## 0x1 已经有了katex的引擎
![image](https://user-images.githubusercontent.com/56435336/78855553-c76ff200-7a56-11ea-8b4c-1583745781ae.png)
## 0x 2 但是还是不太清楚yun主题的要怎样配置才能支持
*这是我在yun.yml的配置*
![image](https://user-images.githubusercontent.com/56435336/78855622-fdad7180-7a56-11ea-9b44-c1c0fbf13aad.png) 
--------
*这是我在站点目录下的配置*
![image](https://user-images.githubusercontent.com/56435336/78855798-7ca2aa00-7a57-11ea-85b5-3b392ca156ca.png)
---
*结果*
![image](https://user-images.githubusercontent.com/56435336/78855950-e1f69b00-7a57-11ea-8d92-488385d426f5.png)

**Comment by YunYouJun** [comment]
Hello, `Yun` 已原生支持使用 `KaTeX` 书写公式。

相关说明见 [第三方支持 - KaTeX](https://yun.yunyoujun.cn/guide/third-party-support.html#katex)

> 正所谓：文档读百遍，其意自现。

仅在需要使用 KaTeX 的文章头部开启，以优化其他不需要使用 KaTeX 的页面速度。（也可选择全局开启。）

```md
---
title: xxx
katex: true
---
```

与主题 [Yun](https://github.com/YunYouJun/hexo-theme-yun) 相关的问题请到 [Issues · hexo-theme-yun](https://github.com/YunYouJun/hexo-theme-yun/issues) 处提问。

请在您觉得问题得到解决时，自行关闭此处 Issue。

**Comment by chenlvtang** [comment]
感谢:smile:
